#!/bin/sh
nasm -fbin pixl1b.asm -o pixl1b.bin
used=$(wc -c < GOS.bin)
echo Used: $used
echo Remaining: $((512 - $used))
if [ $used==512 ]; then
    qemu-system-x86_64 -drive file=pixl1b.bin,format=raw
fi
